source:
  symbol: "US_ISM_MFC_EMPL"
  full_name: "ISM Manufacturing Employment"
  url: "https://www.mql5.com/en/economic-calendar/united-states/ism-manufacturing-employment/export"
  original_file_name: "united-states.ism-manufacturing-employment.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
