source:
  symbol: "HD"
  full_name: "The Home Depot, Inc. (HD)"
  url: "https://query1.finance.yahoo.com/v7/finance/download/HD?period1=369964800&period2=1602028800&interval=1d&events=history"
  original_file_name: "HD.csv"
  snapshot_path: "/Users/uki/REPOS/MarketIndicators.jl/OLD/src/DATA/original/HD.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
