source:
  symbol: "US_HOUS_STRS_M"
  full_name: "United States Housing Starts m/m"
  url: "https://www.mql5.com/en/economic-calendar/united-states/housing-starts-mm/export"
  original_file_name: "united-states.housing-starts-mm.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
