source:
  symbol: "GOLD"
  full_name: "Gold Dec 20 (GC=F)"
  url: "https://query1.finance.yahoo.com/v7/finance/download/GC=F?period1=967593600&period2=1602028800&interval=1d&events=history"
  original_file_name: "GOLD.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
