source:
  symbol: "ATRFX"
  full_name: "Target ATRFX"
  url: "https://query1.finance.yahoo.com/v7/finance/download/ATRFX?period1=315532800&period2=1704067200&interval=1d&events=history&includeAdjustedClose=true"
  original_file_name: "ATRFX.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
