source:
  symbol: "BYDDF"
  full_name: "BYD Company Limited (BYDDF)"
  url: "https://query1.finance.yahoo.com/v7/finance/download/BYDDF?period1=1234483200&period2=1607299200&interval=1d&events=history&includeAdjustedClose=true"
  original_file_name: "BYDDF.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
