source:
  symbol: "US_BUILD_PERM"
  full_name: "United States Building Permits"
  url: "https://www.mql5.com/en/economic-calendar/united-states/building-permits/export"
  original_file_name: "united-states.building-permits.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
