source:
  symbol: "QCOM"
  full_name: "QUALCOMM Incorporated (QCOM)"
  url: "https://query1.finance.yahoo.com/v7/finance/download/QCOM?period1=692582400&period2=1607990400&interval=1d&events=history&includeAdjustedClose=true"
  original_file_name: "QCOM.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
