source:
  symbol: "US_UNEMPLOY_RATE"
  full_name: "United States Unemployment Rate"
  url: "https://www.mql5.com/en/economic-calendar/united-states/unemployment-rate/export"
  original_file_name: "united-states.unemployment-rate.csv"
output:
  raw_dir: "../../OUTPUT/raw"
  metadata_dir: "../../OUTPUT/metadata"
